FROM ubuntu:16.04

ENV DAEMON_RUN=true
ENV SPARK_VERSION=2.4.4
ENV HADOOP_VERSION=2.6
ENV SCALA_VERSION=2.12.4
ENV SCALA_HOME=/usr/share/scala

RUN apt update -y    
RUN apt-get update -y

RUN apt update -y
RUN apt-get install -y python-software-properties
RUN apt-get install -y software-properties-common
RUN add-apt-repository --remove ppa:zeal-developers/ppa
RUN apt-get update -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update -y
RUN apt-get install -y zeal
RUN apt-get install -y python3.6 wget
RUN ls -l /usr/bin | grep python | rm /usr/bin/python
RUN ln -sf /usr/bin/python3.6 /usr/bin/python
#RUN wget https://bootstrap.pypa.io/get-pip.py  --no-check-certificate
#RUN python get-pip.py
RUN apt-get install -y python3-pip
RUN ln -sf /usr/bin/pip3 /usr/bin/pip
RUN pip3 install --upgrade pip

RUN pip install fake_useragent selenium numpy pyspark pymongo pyzmq
RUN pip install python-dateutil==2.8.1 argh
RUN pip install pytz==2019.3 hdfs imageio==2.6.1
RUN pip install six==1.13.0 opencv-python
RUN pip install tensorflow==1.9.0



RUN apt-get install -y bash curl jq && \
    cd "/tmp" && \
    wget --no-verbose "https://downloads.typesafe.com/scala/${SCALA_VERSION}/scala-${SCALA_VERSION}.tgz" && \
    tar xzf "scala-${SCALA_VERSION}.tgz" && \
    mkdir "${SCALA_HOME}" && \
    rm "/tmp/scala-${SCALA_VERSION}/bin/"*.bat && \
    mv "/tmp/scala-${SCALA_VERSION}/bin" "/tmp/scala-${SCALA_VERSION}/lib" "${SCALA_HOME}" && \
    ln -sf "${SCALA_HOME}/bin/"* "/usr/bin/" && \
    rm -rf "/tmp/"*

RUN apt-get install -y openjdk-8-jdk

#Scala instalation
RUN export PATH="/usr/local/sbt/bin:$PATH" &&  apt update -y && apt install -y ca-certificates wget tar && mkdir -p "/usr/local/sbt" && wget -qO - --no-check-certificate "https://piccolo.link/sbt-0.13.16.tgz" | tar xz -C /usr/local/sbt --strip-components=1 && sbt sbtVersion

RUN wget --no-verbose http://ftp.ntu.edu.tw/Apache/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && tar -xvzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
      && mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} spark \
      && rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
