FROM ubuntu:16.04

ENV DAEMON_RUN=true
ENV SPARK_VERSION=2.4.4
ENV HADOOP_VERSION=2.6
ENV SCALA_VERSION=2.12.4
ENV SCALA_HOME=/usr/share/scala



RUN apt update -y   
RUN apt-get install -y python-software-properties  
RUN apt-get install -y software-properties-common
RUN add-apt-repository --remove ppa:zeal-developers/ppa
RUN apt-get update -y 
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update -y
RUN apt-get install -y zeal 
RUN apt-get install -y python3.6 wget
RUN ls -l /usr/bin | grep python | rm /usr/bin/python  
RUN ln -sf /usr/bin/python3.6 /usr/bin/python
#RUN wget https://bootstrap.pypa.io/get-pip.py  --no-check-certificate
#RUN python get-pip.py
#RUN add-apt-repository ppa:jonathonf/python-3.6
#RUN apt-get update -y
#RUN apt-get clean
#RUN apt-get update -y
RUN apt-get install -y python3-pip
RUN ln -sf /usr/bin/pip3 /usr/bin/pip  



RUN apt-get install -y git ccache junit4 gstreamer1.0-libav libkrb5-dev nasm graphviz libpython3-dev
RUN apt-get install -y wget ca-certificates 
#RUN apt-get update -y
#RUN apt-get build-dep python-imaging
#RUN apt-get -update python3.6
#RUN mv /usr/bin/python3.6 /usr/bin/python
#RUN apt-get install -y gcc gfortran python3-dev build-base wget freetype-dev libpng-dev openblas-dev g++ musl-dev libzmq musl-dev zeromq-dev 



#RUN sudo add-apt-repository ppa:deadsnakes/ppa
#RUN sudo apt-get update
#RUN sudo apt-get install python3.6






RUN apt-get install -y cmake 
RUN pip3 install --upgrade pip
RUN pip install dlib
RUN pip install fake_useragent selenium numpy pyspark pymongo pyzmq imageio==2.6.1
RUN pip install python-dateutil==2.8.1 Django line-bot-sdk face_recognition hdfs
RUN pip install opencv-python argh colorama decorator imutils confluent_kafka 
RUN pip install tensorflow==1.9.0
RUN pip install dlib
RUN pip install jupyter

RUN apt-get install -y bash curl jq && \
    cd "/tmp" && \
    wget "https://downloads.typesafe.com/scala/${SCALA_VERSION}/scala-${SCALA_VERSION}.tgz" && \
    tar xzf "scala-${SCALA_VERSION}.tgz" && \
    mkdir "${SCALA_HOME}" && \
    rm "/tmp/scala-${SCALA_VERSION}/bin/"*.bat && \
    mv "/tmp/scala-${SCALA_VERSION}/bin" "/tmp/scala-${SCALA_VERSION}/lib" "${SCALA_HOME}" && \
    ln -s "${SCALA_HOME}/bin/"* "/usr/bin/" && \
    #apt-get rm .build-dependencies && \
    rm -rf "/tmp/"*
RUN apt-get install -y wget git ntp
#RUN apt-get install -y java-1.8.0-openjdk.x86_64 java-1.8.0-openjdk-devel.x86_64
RUN apt-get install -y openjdk-8-jdk

#Scala instalation
RUN export PATH="/usr/local/sbt/bin:$PATH" &&  apt-get update && apt-get install -y ca-certificates wget tar && mkdir -p "/usr/local/sbt" && wget -qO - --no-check-certificate "https://piccolo.link/sbt-0.13.16.tgz" | tar xz -C /usr/local/sbt --strip-components=1 && sbt sbtVersion

RUN wget http://ftp.ntu.edu.tw/Apache/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && tar -xvzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
      && mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} spark \
      && rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
